package application;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.AnchorPane;

public class LoginController {
	@FXML
	private AnchorPane labelMensaje2;
	@FXML
	private Label labelMensaje;

	// Event Listener on Button.onAction
	@FXML
	public void btnCrear(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnInicio(ActionEvent event) {
		// TODO Autogenerated
	}
}
